<?php

namespace backend\modules\Reservations\models;

use backend\modules\MadActiveRecord\models\MadActiveRecord;
use Yii;
use yii\db\ActiveRecord;

class ReservationsInfo extends Reservations
{


    public function afterFind()
    {
        parent::afterFind();

        $myjson=json_decode($this->data);
        if($myjson){
            $this->setAttribute("fname",$myjson->orderDetails->billing_first_name);
            $this->setAttribute("lname",$myjson->orderDetails->billing_last_name);
        }

    }
    public function beforeSave($insert)
    {

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub



    }

    public function attributes() {
        $attributes = parent::attributes();
        return array_merge($attributes, [
            'fname','lname'
        ]);
    }

    public function getData(){
        return $this->data;

    }

    public static function getList()
    {
        return ArrayHelper::map(self::find()->all(), 'bookingId', 'bookingDate');
    }



}